import copy
import inspect
import logging
import os
import secrets
import time

import numpy as np
import openmm.app

from ._abc import Propagator

logger = logging.getLogger(__name__)


class OpenMMReport:
    """Describes a report generated by an OpenMM reporter.

    Parameters
    ----------
    reporter_type : type
        Reporter type.
    filename : str
        Name of the output file.
    report_interval : int
        Interval (in time steps) at which the report is generated.
    options : Mapping[str, Any], optional
        Keyword arguments provided to the `reporter_type` constructor.

    Examples
    --------

    >>> import westpa
    >>> import openmm.app
    >>> westpa.OpenMMReport(
    ...     reporter_type=openmm.app.XTCReporter,
    ...     filename='traj.xtc',
    ...     report_interval=1000,
    ... )
    OpenMMReport(reporter_type=<class 'openmm.app.xtcreporter.XTCReporter'>,filename='traj.xtc', report_interval=1000, options={})

    """

    def __init__(self, *, reporter_type, filename, report_interval, options=None):
        self.reporter_type = reporter_type
        self.filename = filename
        self.report_interval = report_interval
        self.options = options or {}

    def __repr__(self):
        parameters = inspect.signature(self.__init__).parameters
        args = ', '.join(f'{name}={getattr(self, name)!r}' for name in parameters)
        return type(self).__name__ + '(' + args + ')'


class OpenMMPropagator(Propagator):
    """Molecular dynamics propagator built on the `OpenMM <https://openmm.org/>`_ toolkit.

    This propagator assumes that segment ``initpoint`` and ``endpoint`` values are
    absolute paths to XML files containing serialized OpenMM
    `State <https://docs.openmm.org/latest/api-python/generated/openmm.openmm.State.html>`_
    objects.

    Parameters
    ----------
    topology : openmm.app.Topology
        Topology of the system.
    system : openmm.System
        System (particles, forces, and constraints) to simulate.
    integrator : openmm.Integrator
        Integrator to use for simulating the system.
    steps : int
        Number of time steps to simulate for each segment.
    platform : openmm.Platform, optional
        Platform to use for calculations.
    platform_properties : Mapping[str, str], optional
        Platform-specific properties to pass to the simulation context.
    segment_dir_template : str, default 'traj_segs/{n_iter:06d}/{seg_id:06d}'
        Template string specifying the directory in which to store output for a
        given segment. The string must contain ``{n_iter}`` and ``{seg_id}``
        replacement fields. If a relative path is provided, it is assumed to be
        relative to the current working directory.
    endpoint_filename : str, default 'endpoint.xml'
        Name of the XML file used to store the final microstate of the segment.
    reports : iterable of :class:`OpenMMReport`, optional
        Additional output to report for each segment.
    seed : int or sequence of int, optional
        Seed to initialize the random state. All integer values must be
        non-negative.

    Examples
    --------

    >>> import westpa
    >>> import openmm
    >>> from openmm import app, unit
    >>> forcefield = app.ForceField('amber14-all.xml')
    >>> topology = app.PDBFile('topology.pdb').getTopology()
    >>> system = forcefield.createSystem(
    ...     topology, nonbondedMethod=app.PME, constraints=app.HBonds
    ... )
    >>> integrator = openmm.LangevinIntegrator(
    ...     300 * unit.kelvin, 1 / unit.picosecond, 2 * unit.femtosecond
    ... )
    >>> propagator = westpa.OpenMMPropagator(
    ...     topology=topology,
    ...     system=system,
    ...     integrator=integrator
    ...     steps=1000,
    ... )


    """

    def __init__(
        self,
        *,
        topology,
        system,
        integrator,
        steps,
        platform=None,
        platform_properties=None,
        segment_dir_template='traj_segs/{n_iter:06d}/{seg_id:06d}',
        endpoint_filename="endpoint.xml",
        reports=None,
        seed=None,
    ):
        self.topology = topology
        self.system = system
        self.integrator = integrator
        self.steps = steps
        self.platform = platform
        self.platform_properties = platform_properties
        self.segment_dir_template = os.path.abspath(segment_dir_template)
        self.endpoint_filename = endpoint_filename
        self.reports = list(reports or [])

        seed = seed if seed is not None else secrets.randbits(128)
        logger.info(f'{seed=}')
        self.seed = seed

    def __call__(self, segment):
        # see https://numpy.org/doc/2.2/reference/random/parallel.html#sequence-of-integer-seeds
        rng = np.random.default_rng([segment.seg_id, segment.n_iter, self.seed])

        integrator = copy.copy(self.integrator)  # copy to avoid 'already bound to Context' error
        if hasattr(integrator, 'setRandomNumberSeed'):
            integrator.setRandomNumberSeed(rng.integers(low=1, high=2**31))

        for force in self.system.getForces():
            if hasattr(force, 'setRandomNumberSeed'):
                force.setRandomNumberSeed(rng.integers(low=1, high=2**31))

        simulation = openmm.app.Simulation(
            self.topology,
            self.system,
            integrator,
            platform=self.platform,
            platformProperties=self.platform_properties,
            state=segment.initpoint,
        )

        segment_dir = self.segment_dir_template.format(n_iter=segment.n_iter, seg_id=segment.seg_id)
        os.makedirs(segment_dir)

        for report in self.reports:
            file = os.path.join(segment_dir, report.filename)
            reporter = report.reporter_type(file, report.report_interval, **report.options)
            simulation.reporters.append(reporter)

        start = time.time()
        try:
            simulation.step(self.steps)
        except openmm.OpenMMException as e:
            segment.mark_as_failed(str(e))
        else:
            endpoint_file = os.path.join(segment_dir, self.endpoint_filename)
            simulation.saveState(endpoint_file)
            segment.endpoint = endpoint_file
            segment.walltime = time.time() - start

        return segment

    def __repr__(self):
        parameters = inspect.signature(self.__init__).parameters
        args = ', '.join(f'{name}={getattr(self, name)!r}' for name in parameters)
        return type(self).__name__ + '(' + args + ')'
