from ..core._data_manager import DataManager  # noqa


class TrajectoryTree:
    """Interface for analyzing the trajectory data generated by a simulation.

    Parameters
    ----------
    datafile : str or io.BufferedIOBase
        HDF5 file containing data generated by a simulation.
    load_pcoords : bool, default True
        Whether to load progress coordinates when retrieving trajectory data.

    Attributes
    ----------
    load_pcoords : bool

    Methods
    -------
    __getitem__

    """

    def __init__(
        self,
        datafile,
        *,
        load_pcoords=True,
    ):
        self.data_manager = DataManager(datafile)
        self._load_pcoords = None
        self.load_pcoords = load_pcoords

    def open(self):
        self.data_manager.open_backing(mode='r')

    def close(self):
        self.data_manager.close_backing()

    def __enter__(self):
        self.open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
        return False

    @property
    def load_pcoords(self):
        """Whether to load progress coordinates."""
        return self._load_pcoords

    @load_pcoords.setter
    def load_pcoords(self, value):
        if not isinstance(value, bool):
            raise TypeError("'load_pcoords' must be True or False")
        self._load_pcoords = value

    def __getitem__(self, key):
        """Retrieve one or more trajectory segments.

        Parameters
        ----------
        key : tuple[int, int | list[int] | ellipsis]
            Tuple of the form ``(n_iter, seg_ids)``, where ``seg_ids`` is a
            single segment index, a list of segment indices, or an ellipsis.
            In the last case, all the segments in iteration ``n_iter`` will
            be returned.

        Returns
        -------
        segments : :class:`Segment` or list of :class:`Segment`
            Segment or segments specified by `key`.

        """
        n_iter, seg_ids = key
        with self:
            if isinstance(seg_ids, int):
                seg_ids = [seg_ids]
                return self.data_manager.get_segments(n_iter, seg_ids, self.load_pcoords)[0]
            else:
                seg_ids = None if seg_ids is Ellipsis else seg_ids
                return self.data_manager.get_segments(n_iter, seg_ids, self.load_pcoords)

    def get_parent_ids(self, n_iter, seg_ids=None):
        with self:
            return self._data_manager.get_parent_ids(n_iter, seg_ids=seg_ids)

    def parent(self, segment):
        if segment.initpoint_type == segment.InitPointType.NEWTRAJ:
            return None
        else:
            return self[segment.n_iter - 1, segment.parent_id]

    def trace(self, segment):
        segments = [segment]
        while parent := self.parent(segment):
            segments.append(parent)
        return reversed(segments)
