import logging
import operator

import numpy as np
from sortedcontainers import SortedSet

logger = logging.getLogger(__name__)

EPS = np.finfo(np.float64).eps


class Bin(SortedSet):
    """A subset of trajectory segments in a partition generated by a bin mapper.

    Attributes
    ----------
    label : str or None
    count : int
    weight : float

    """

    def __init__(self, iterable=None, label=None):
        super().__init__(iterable, key=operator.attrgetter('weight'))
        self._label = label

    def __repr__(self):
        names = ['label', 'count', 'weight']
        attrs = ', '.join(f'{name}={getattr(self, name)!r}' for name in names)
        return f'<{self.__class__.__name__} at {hex(id(self))}, {attrs}>'

    @property
    def label(self):
        """Bin label."""
        return self._label

    @property
    def count(self):
        """Number of segments in the bin."""
        return len(self)

    @property
    def weight(self):
        """Total weight of all segments in the bin."""
        return sum(map(self.key, self))

    def reweight(self, new_weight):
        """Reweight the bin by linearly rescaling the segment weights.

        Parameters
        ----------
        new_weight : float
            New total weight of the bin.

        """
        if len(self) == 0 and new_weight == 0:
            return

        if len(self) == 0 and new_weight != 0:
            raise ValueError('cannot reweight empty ParticleCollection')

        current_weight = self.weight
        logger.debug('reweighting collection of {:d} particles from {:g} to {:g}'.format(len(self), current_weight, new_weight))
        assert (new_weight == 0 and current_weight == 0) or new_weight > 0

        wrat = new_weight / current_weight
        for p in self:
            p.weight *= wrat

        logger.debug('new weight: {:g}'.format(self.weight))
        assert abs(new_weight - self.weight) <= EPS * len(self)
