import abc
import itertools
import logging
import math
import operator
import secrets

import numpy as np

from westpa.core.binning import Bin, BinMapper, NopMapper
from westpa.core.segment import Segment
from westpa.core.we_driver import ConsistencyError

logger = logging.getLogger(__name__)
weight_getter = operator.attrgetter('weight')


class Resampler(abc.ABC):
    """Defines a method for splitting and merging trajectories.

    Parameters
    ----------
    bin_mapper : BinMapper, default NOPBinMapper()
        Bin mapper for assigning trajectories to bins. By default, all
        the trajectories are assigned to a single bin.
    bin_target_counts : int or sequence of int, default 1
        Target number of trajectories for each bin. If an integer is provided,
        the value will be applied to all the bins. If a sequence is provided,
        its length must match ``bin_mapper.nbins``.
    adjust_counts : bool, default True
        Whether to adjust the number of segments in occupied bins to exactly
        match the target count. This is done by iteratively merging the two
        lowest-weight segments (if above the target count) or by iteratively
        splitting the highest-weight segment (if below the target count).
    smallest_allowed_weight : float, default 1e-100
        Smallest allowed weight.
    larget_allowed_weight : float, default 1.0
        Largest allowed weight.
    seed : int or sequence of int, optional
        Seed to initialize the pseudo-random number generator. Integer values
        must be non-negative.

    Attributes
    ----------
    bin_mapper : BinMapper
    bin_target_counts : numpy.ndarray
    adjust_counts : bool
    smallest_allowed_weight : float
    largest_allowed_weight : float
    rng : numpy.random.Generator

    """

    @abc.abstractmethod
    def resample(self, bin, target_count):
        """Resample a given bin.

        Parameters
        ----------
        bin : set of Segment
            Bin to resample.
        target_count : int
            Target number of trajectories (allocation) for the bin.

        Returns
        -------
        iterable of Segment
            New set of segments generated by resampling `bin`.

        """
        ...

    def __init__(
        self,
        *,
        bin_mapper=None,
        bin_target_counts=1,
        adjust_counts=True,
        smallest_allowed_weight=1e-100,
        largest_allowed_weight=1.0,
        seed=None,
    ):
        self._bin_mapper = None
        self._bin_target_counts = None
        self.update_bins(bin_mapper, bin_target_counts)
        self.adjust_counts = adjust_counts

        self._smallest_allowed_weight = None
        self._largest_allowed_weight = None
        self.set_weight_thresholds(smallest_allowed_weight, largest_allowed_weight)

        seed = seed if seed is not None else secrets.randbits(128)
        self._rng = np.random.default_rng(seed)
        logger.info(f'{seed=}')

    def __call__(self, segments):
        binning = self.bin_mapper.map(segments)
        for ibin, bin in binning.items():
            if bin.count == 0:
                continue

            target_count = self.bin_target_counts[ibin]
            segments = self.resample(bin, target_count)

            new_weight = sum(segment.weight for segment in segments)
            if not math.isclose(new_weight, bin.weight, abs_tol=1e-12):
                raise ConsistencyError('the resample() method must preserve the bin weight')

            binning[ibin] = Bin(segments, label=bin.label)

        # post-processing
        for ibin, bin in binning.items():
            if self.adjust_counts:
                target_count = self.bin_target_counts[ibin]
                self._adjust_count(bin, target_count)

            self._split_by_threshold(bin)
            self._merge_by_threshold(bin)
            for segment in bin:
                if not (self.smallest_allowed_weight <= segment.weight <= self.largest_allowed_weight):
                    logger.warning(
                        f'Unable to fulfill weight threshold conditions for {segment}. '
                        'The given threshold range is likely too small.'
                    )

        segments = list(itertools.chain(*binning.values()))

        # consistency checks
        weights = np.array([segment.weight for segment in segments])
        if (weights <= 0).any():
            raise ConsistencyError('segment weights must be greater than 0')
        if not math.isclose(weights.sum(), 1.0, abs_tol=1e-12):
            raise ConsistencyError('segment weights must sum to 1')

        return segments

    @staticmethod
    def split(segment, bin, m=2):
        """Split a trajectory segment into two or more copies.

        Parameters
        ----------
        segment : Segment
            Segment to split.
        bin : Bin
            Bin to which the segment belongs.
        m : int, default 2
            Number of copies to split `segment` into.

        Returns
        -------
        set of Segment
            Segments created by splitting `segment` into `m` equally weighted copies.

        """
        if not isinstance(m, int):
            raise TypeError("'m' must be an integer")
        if not m >= 2:
            raise ValueError("'m' must be greater than or equal to 2")

        new_weight = segment.weight / m
        new_segments = {
            Segment(
                n_iter=segment.n_iter,
                seg_id=segment.seg_id,
                weight=new_weight,
                parent_id=segment.parent_id,
                wtg_parent_ids=segment.wtg_parent_ids,
                initial_state=segment.initial_state,
                final_state=segment.final_state,
                pcoord=segment.pcoord,
                data=segment.data,
            )
            for _ in range(m)
        }

        bin.remove(segment)
        bin.update(new_segments)

        return new_segments

    def merge(self, segments, bin):
        """Merge multiple trajectory segments into a single segment. The
        surviving segment is chosen randomly according to weight.

        Parameters
        ----------
        segments : iterable of Segment
            Segments to merge.
        bin : Bin
            Bin to which the segments belong.

        Returns
        -------
        Segment
            Copy of the surviving segment, assigned the total weight of
            `segments`.

        """
        segments = list(segments)
        weights = np.array([segment.weight for segment in segments])
        total_weight = weights.sum()

        choice = self.rng.choice(segments, p=weights / total_weight)
        new_segment = Segment(
            n_iter=segments[0].n_iter,
            seg_id=choice.seg_id,
            weight=total_weight,
            parent_id=choice.parent_id,
            wtg_parent_ids=set.union(*(segment.wtg_parent_ids for segment in segments)),
            initial_state=choice.initial_state,
            final_state=choice.final_state,
            pcoord=choice.pcoord,
            data=choice.data,
        )

        bin.difference_update(segments)
        bin.add(new_segment)

        return new_segment

    def update_bins(self, bin_mapper, bin_target_counts):
        """Update the bin mapper and target counts.

        Parameters
        ----------
        bin_mapper : BinMapper or None
            Bin mapper for assigning trajectories to bins. If None, all the
            trajectories will be assigned to a single bin.
        bin_target_counts : int or sequence of int
            Target number of trajectories for each bin. Values must be positive.

        """
        if bin_mapper is None:
            bin_mapper = NopMapper()
        elif not isinstance(bin_mapper, BinMapper):
            raise TypeError("'bin_mapper' must be a BinMapper object")

        if isinstance(bin_target_counts, int):
            bin_target_counts = np.repeat(bin_target_counts, bin_mapper.nbins)
        else:
            bin_target_counts = np.asarray(bin_target_counts, dtype=int)
            if not len(bin_target_counts) == bin_mapper.nbins:
                raise ValueError("length of 'bin_target_counts' must equal the number of bins")
        if (bin_target_counts <= 0).any():
            raise ValueError("'bin_target_counts' must be positive")

        self._bin_mapper = bin_mapper
        self._bin_target_counts = bin_target_counts

    @property
    def bin_mapper(self):
        """Bin mapper."""
        return self._bin_mapper

    @property
    def bin_target_counts(self):
        """Target number of segments for each bin."""
        return self._bin_target_counts

    def set_weight_thresholds(self, smallest_allowed_weight, largest_allowed_weight):
        """Set the minimum and maximum allowed weights.

        Parameters
        ----------
        smallest_allowed_weight : float
            Minimum allowed weight.
        largest_allowed_weight : float
            Maximum allowed weight.

        """
        if not (0 < smallest_allowed_weight < 1):
            raise ValueError("'smallest_allowed_weight' must be between 0 and 1")
        if not (smallest_allowed_weight < largest_allowed_weight <= 1):
            raise ValueError("'largest_allowed_weight' must be between 'smallest_allowed_weight' and 1")
        self._smallest_allowed_weight = smallest_allowed_weight
        self._largest_allowed_weight = largest_allowed_weight

    @property
    def smallest_allowed_weight(self):
        """Minimum allowed weight."""
        return self._smallest_allowed_weight

    @property
    def largest_allowed_weight(self):
        """Maximum allowed weight."""
        return self._largest_allowed_weight

    @property
    def rng(self):
        """Pseudo-random number generator."""
        return self._rng

    def _adjust_count(self, bin, target_count):
        while len(bin) < target_count:
            logger.debug('adjusting counts by splitting')
            self.split(bin[-1], bin, m=2)
        while len(bin) > target_count:
            logger.debug('adjusting counts by merging')
            self.merge(bin[:2], bin)

    def _split_by_threshold(self, bin):
        index = bin.bisect_key(self.largest_allowed_weight)
        to_split = bin[index:]
        for segment in to_split:
            m = math.ceil(segment.weight / self.largest_allowed_weight)
            self.split(segment, bin, m=m)

    def _merge_by_threshold(self, bin):
        while True:
            index = bin.bisect_key(self.smallest_allowed_weight)
            to_merge = bin[:index]
            if len(to_merge) < 2:
                return
            self.merge(to_merge, bin)
